from __future__ import annotations

import json
import re

from . import __version__
from .models import Finding, InputAction
from .policy import InputPolicy
from .rule_help import catalog_for, explain_rule


def render_text_report(
    actions: list[InputAction], findings: list[Finding], policy: InputPolicy | None = None
) -> str:
    lines = [
        "Godot Input Map Auditor",
        f"Scanned {len(actions)} action(s): {len(findings)} finding(s).",
    ]
    for action in actions:
        devices = ", ".join(sorted(action.devices)) or "none"
        group = policy.group_for_action(action.name) if policy else None
        group_text = f" [{group}]" if group else ""
        lines.append(f"- {action.name}{group_text}: {devices} ({len(action.events)} event(s))")
    if findings:
        for finding in findings:
            help_text = explain_rule(finding.rule_id)
            lines.append(f"[{finding.severity.upper()}] {help_text['title']}: {finding.message}")
            lines.append(f"  Why it matters: {help_text['explanation']}")
    else:
        lines.append("No findings.")
    return "\n".join(lines)


def render_json_report(
    actions: list[InputAction], findings: list[Finding], policy: InputPolicy | None = None
) -> str:
    payload = {
        "tool": "godot-input-map-auditor",
        "metadata": {
            "schema_version": "1.1",
            "tool_version": __version__,
            "report_kind": "input_map_audit",
            "formats": ["text", "json", "sarif"],
        },
        "summary": {
            "actions": len(actions),
            "groups": len(policy.action_groups) if policy else 0,
            "findings": len(findings),
            "errors": sum(1 for finding in findings if finding.severity == "error"),
            "warnings": sum(1 for finding in findings if finding.severity == "warning"),
        },
        "policy": policy.to_dict() if policy else None,
        "actions": [_action_to_dict(action, policy) for action in actions],
        "rules": catalog_for({finding.rule_id for finding in findings}),
        "findings": [finding.to_dict() for finding in findings],
    }
    return json.dumps(payload, indent=2, sort_keys=True)


def render_sarif_report(
    actions: list[InputAction], findings: list[Finding], policy: InputPolicy | None = None
) -> str:
    rules = {}
    results = []
    for finding in findings:
        help_text = explain_rule(finding.rule_id)
        rules.setdefault(
            finding.rule_id,
            {
                "id": finding.rule_id,
                "name": help_text["title"],
                "shortDescription": {"text": help_text["explanation"]},
            },
        )
        results.append(
            {
                "ruleId": finding.rule_id,
                "level": _sarif_level(finding.severity),
                "message": {"text": finding.message},
                "locations": [
                    {
                        "physicalLocation": {"artifactLocation": {"uri": "project.godot"}},
                        "logicalLocations": [{"name": finding.action or "input"}],
                    }
                ],
            }
        )
    payload = {
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "version": "2.1.0",
        "runs": [
            {
                "tool": {
                    "driver": {
                        "name": "godot-input-map-auditor",
                        "rules": list(rules.values()),
                    }
                },
                "results": results,
            }
        ],
    }
    return json.dumps(payload, indent=2, sort_keys=True)


def render_markdown_reference(actions: list[InputAction], policy: InputPolicy | None = None) -> str:
    lines = ["# Input Reference", ""]
    if policy:
        lines.extend(["| Action | Group | Devices | Events |", "|---|---|---|---:|"])
    else:
        lines.extend(["| Action | Devices | Events |", "|---|---|---:|"])
    for action in sorted(actions, key=lambda item: item.name):
        devices = ", ".join(sorted(action.devices)) or "none"
        if policy:
            group = policy.group_for_action(action.name) or ""
            lines.append(f"| {action.name} | {group} | {devices} | {len(action.events)} |")
        else:
            lines.append(f"| {action.name} | {devices} | {len(action.events)} |")
    if not actions:
        lines.append("| none | none | none | 0 |" if policy else "| none | none | 0 |")
    lines.append("")
    return "\n".join(lines)


def render_gdscript_constants(actions: list[InputAction]) -> str:
    lines = [
        "class_name InputActions",
        "",
        "# Generated by godot-input-map-auditor.",
    ]
    for action in sorted(actions, key=lambda item: item.name):
        lines.append(f'const {_constant_name(action.name)} = "{action.name}"')
    lines.append("")
    return "\n".join(lines)


def _constant_name(action: str) -> str:
    value = re.sub(r"[^A-Za-z0-9]+", "_", action).strip("_").upper()
    if not value:
        return "ACTION"
    if value[0].isdigit():
        return f"ACTION_{value}"
    return value


def _action_to_dict(action: InputAction, policy: InputPolicy | None) -> dict[str, object]:
    payload = action.to_dict()
    if policy:
        payload["group"] = policy.group_for_action(action.name)
        payload["required_devices"] = sorted(policy.required_devices_for_action(action.name))
    return payload


def _sarif_level(severity: str) -> str:
    if severity == "error":
        return "error"
    if severity == "warning":
        return "warning"
    return "note"
